name: Sui Move Coverage Tests

on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mysten/sui-tools:ci
    steps:
      - uses: actions/checkout@v4
      - name: coverage test
        run: echo "Sui move docker doesn't support coverage flag"  # sui move test --coverage
      # - name: Check test coverage
      #   run:  ./scripts/report_test_coverage.sh
