name: Sui Move tests

on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mysten/sui-tools:ci
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: sui move build
      - name: Run test
        run: sui move test
